Repository nim-lang/website, pull requests merged in 2020-10, with the labels that each got.

#215 add Hacktoberfest post
  jekyll/_posts/2020-10-01-hacktoberfest-with-nim.md
Labels: enhancement

#229 Add Kiloneie Nim For Beginners playlist
  jekyll/learn.html
Labels: enhancement

#228 Change default donation website
  jekyll/donate.md
Labels: enhancement, hacktoberfest-accepted

#227 Some changes to the FAQ
  jekyll/faq.md
Labels: enhancement, hacktoberfest-accepted

#230 "Introduction to ARC/ORC in Nim" guest post
  jekyll/_posts/2020-10-15-introduction-to-arc-orc-in-nim.md
  jekyll/assets/news/images/yardanico-arc/cycle.svg
Labels: enhancement

#234 version 1.4.0 released
  jekyll/_config.yml
  jekyll/_posts/2020-10-16-version-140-released.md
Labels: hacktoberfest-accepted

#241 versions 1.2.8 and 1.0.10 released
  jekyll/_posts/2020-10-27-versions-128-and-1010-released.md
Labels: enhancement
